# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/carl/Desktop/EPITA/Cycle Ingenieur/ING1/epita-ing-assistants-acu-42sh-2025-paris-53"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/carl/Desktop/EPITA/Cycle Ingenieur/ING1/epita-ing-assistants-acu-42sh-2025-paris-53"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/carl/Desktop/EPITA/Cycle Ingenieur/ING1/epita-ing-assistants-acu-42sh-2025-paris-53/CMakeFiles" "/Users/carl/Desktop/EPITA/Cycle Ingenieur/ING1/epita-ing-assistants-acu-42sh-2025-paris-53//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/carl/Desktop/EPITA/Cycle Ingenieur/ING1/epita-ing-assistants-acu-42sh-2025-paris-53/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 42sh

# Build rule for target.
42sh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 42sh
.PHONY : 42sh

# fast build rule for target.
42sh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/build
.PHONY : 42sh/fast

src/builtins/break.o: src/builtins/break.c.o
.PHONY : src/builtins/break.o

# target to build an object file
src/builtins/break.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/break.c.o
.PHONY : src/builtins/break.c.o

src/builtins/break.i: src/builtins/break.c.i
.PHONY : src/builtins/break.i

# target to preprocess a source file
src/builtins/break.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/break.c.i
.PHONY : src/builtins/break.c.i

src/builtins/break.s: src/builtins/break.c.s
.PHONY : src/builtins/break.s

# target to generate assembly for a file
src/builtins/break.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/break.c.s
.PHONY : src/builtins/break.c.s

src/builtins/cd.o: src/builtins/cd.c.o
.PHONY : src/builtins/cd.o

# target to build an object file
src/builtins/cd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/cd.c.o
.PHONY : src/builtins/cd.c.o

src/builtins/cd.i: src/builtins/cd.c.i
.PHONY : src/builtins/cd.i

# target to preprocess a source file
src/builtins/cd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/cd.c.i
.PHONY : src/builtins/cd.c.i

src/builtins/cd.s: src/builtins/cd.c.s
.PHONY : src/builtins/cd.s

# target to generate assembly for a file
src/builtins/cd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/cd.c.s
.PHONY : src/builtins/cd.c.s

src/builtins/continue.o: src/builtins/continue.c.o
.PHONY : src/builtins/continue.o

# target to build an object file
src/builtins/continue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/continue.c.o
.PHONY : src/builtins/continue.c.o

src/builtins/continue.i: src/builtins/continue.c.i
.PHONY : src/builtins/continue.i

# target to preprocess a source file
src/builtins/continue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/continue.c.i
.PHONY : src/builtins/continue.c.i

src/builtins/continue.s: src/builtins/continue.c.s
.PHONY : src/builtins/continue.s

# target to generate assembly for a file
src/builtins/continue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/continue.c.s
.PHONY : src/builtins/continue.c.s

src/builtins/dot.o: src/builtins/dot.c.o
.PHONY : src/builtins/dot.o

# target to build an object file
src/builtins/dot.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/dot.c.o
.PHONY : src/builtins/dot.c.o

src/builtins/dot.i: src/builtins/dot.c.i
.PHONY : src/builtins/dot.i

# target to preprocess a source file
src/builtins/dot.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/dot.c.i
.PHONY : src/builtins/dot.c.i

src/builtins/dot.s: src/builtins/dot.c.s
.PHONY : src/builtins/dot.s

# target to generate assembly for a file
src/builtins/dot.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/dot.c.s
.PHONY : src/builtins/dot.c.s

src/builtins/echo.o: src/builtins/echo.c.o
.PHONY : src/builtins/echo.o

# target to build an object file
src/builtins/echo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/echo.c.o
.PHONY : src/builtins/echo.c.o

src/builtins/echo.i: src/builtins/echo.c.i
.PHONY : src/builtins/echo.i

# target to preprocess a source file
src/builtins/echo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/echo.c.i
.PHONY : src/builtins/echo.c.i

src/builtins/echo.s: src/builtins/echo.c.s
.PHONY : src/builtins/echo.s

# target to generate assembly for a file
src/builtins/echo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/echo.c.s
.PHONY : src/builtins/echo.c.s

src/builtins/exit.o: src/builtins/exit.c.o
.PHONY : src/builtins/exit.o

# target to build an object file
src/builtins/exit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/exit.c.o
.PHONY : src/builtins/exit.c.o

src/builtins/exit.i: src/builtins/exit.c.i
.PHONY : src/builtins/exit.i

# target to preprocess a source file
src/builtins/exit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/exit.c.i
.PHONY : src/builtins/exit.c.i

src/builtins/exit.s: src/builtins/exit.c.s
.PHONY : src/builtins/exit.s

# target to generate assembly for a file
src/builtins/exit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/exit.c.s
.PHONY : src/builtins/exit.c.s

src/builtins/export.o: src/builtins/export.c.o
.PHONY : src/builtins/export.o

# target to build an object file
src/builtins/export.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/export.c.o
.PHONY : src/builtins/export.c.o

src/builtins/export.i: src/builtins/export.c.i
.PHONY : src/builtins/export.i

# target to preprocess a source file
src/builtins/export.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/export.c.i
.PHONY : src/builtins/export.c.i

src/builtins/export.s: src/builtins/export.c.s
.PHONY : src/builtins/export.s

# target to generate assembly for a file
src/builtins/export.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/export.c.s
.PHONY : src/builtins/export.c.s

src/builtins/true_false.o: src/builtins/true_false.c.o
.PHONY : src/builtins/true_false.o

# target to build an object file
src/builtins/true_false.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/true_false.c.o
.PHONY : src/builtins/true_false.c.o

src/builtins/true_false.i: src/builtins/true_false.c.i
.PHONY : src/builtins/true_false.i

# target to preprocess a source file
src/builtins/true_false.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/true_false.c.i
.PHONY : src/builtins/true_false.c.i

src/builtins/true_false.s: src/builtins/true_false.c.s
.PHONY : src/builtins/true_false.s

# target to generate assembly for a file
src/builtins/true_false.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/true_false.c.s
.PHONY : src/builtins/true_false.c.s

src/builtins/unset.o: src/builtins/unset.c.o
.PHONY : src/builtins/unset.o

# target to build an object file
src/builtins/unset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/unset.c.o
.PHONY : src/builtins/unset.c.o

src/builtins/unset.i: src/builtins/unset.c.i
.PHONY : src/builtins/unset.i

# target to preprocess a source file
src/builtins/unset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/unset.c.i
.PHONY : src/builtins/unset.c.i

src/builtins/unset.s: src/builtins/unset.c.s
.PHONY : src/builtins/unset.s

# target to generate assembly for a file
src/builtins/unset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/builtins/unset.c.s
.PHONY : src/builtins/unset.c.s

src/interpreter/environment.o: src/interpreter/environment.c.o
.PHONY : src/interpreter/environment.o

# target to build an object file
src/interpreter/environment.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/environment.c.o
.PHONY : src/interpreter/environment.c.o

src/interpreter/environment.i: src/interpreter/environment.c.i
.PHONY : src/interpreter/environment.i

# target to preprocess a source file
src/interpreter/environment.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/environment.c.i
.PHONY : src/interpreter/environment.c.i

src/interpreter/environment.s: src/interpreter/environment.c.s
.PHONY : src/interpreter/environment.s

# target to generate assembly for a file
src/interpreter/environment.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/environment.c.s
.PHONY : src/interpreter/environment.c.s

src/interpreter/function_list.o: src/interpreter/function_list.c.o
.PHONY : src/interpreter/function_list.o

# target to build an object file
src/interpreter/function_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/function_list.c.o
.PHONY : src/interpreter/function_list.c.o

src/interpreter/function_list.i: src/interpreter/function_list.c.i
.PHONY : src/interpreter/function_list.i

# target to preprocess a source file
src/interpreter/function_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/function_list.c.i
.PHONY : src/interpreter/function_list.c.i

src/interpreter/function_list.s: src/interpreter/function_list.c.s
.PHONY : src/interpreter/function_list.s

# target to generate assembly for a file
src/interpreter/function_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/function_list.c.s
.PHONY : src/interpreter/function_list.c.s

src/interpreter/interpreter.o: src/interpreter/interpreter.c.o
.PHONY : src/interpreter/interpreter.o

# target to build an object file
src/interpreter/interpreter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/interpreter.c.o
.PHONY : src/interpreter/interpreter.c.o

src/interpreter/interpreter.i: src/interpreter/interpreter.c.i
.PHONY : src/interpreter/interpreter.i

# target to preprocess a source file
src/interpreter/interpreter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/interpreter.c.i
.PHONY : src/interpreter/interpreter.c.i

src/interpreter/interpreter.s: src/interpreter/interpreter.c.s
.PHONY : src/interpreter/interpreter.s

# target to generate assembly for a file
src/interpreter/interpreter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/interpreter.c.s
.PHONY : src/interpreter/interpreter.c.s

src/interpreter/redirections.o: src/interpreter/redirections.c.o
.PHONY : src/interpreter/redirections.o

# target to build an object file
src/interpreter/redirections.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/redirections.c.o
.PHONY : src/interpreter/redirections.c.o

src/interpreter/redirections.i: src/interpreter/redirections.c.i
.PHONY : src/interpreter/redirections.i

# target to preprocess a source file
src/interpreter/redirections.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/redirections.c.i
.PHONY : src/interpreter/redirections.c.i

src/interpreter/redirections.s: src/interpreter/redirections.c.s
.PHONY : src/interpreter/redirections.s

# target to generate assembly for a file
src/interpreter/redirections.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/redirections.c.s
.PHONY : src/interpreter/redirections.c.s

src/interpreter/variable_list.o: src/interpreter/variable_list.c.o
.PHONY : src/interpreter/variable_list.o

# target to build an object file
src/interpreter/variable_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/variable_list.c.o
.PHONY : src/interpreter/variable_list.c.o

src/interpreter/variable_list.i: src/interpreter/variable_list.c.i
.PHONY : src/interpreter/variable_list.i

# target to preprocess a source file
src/interpreter/variable_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/variable_list.c.i
.PHONY : src/interpreter/variable_list.c.i

src/interpreter/variable_list.s: src/interpreter/variable_list.c.s
.PHONY : src/interpreter/variable_list.s

# target to generate assembly for a file
src/interpreter/variable_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/interpreter/variable_list.c.s
.PHONY : src/interpreter/variable_list.c.s

src/lexer/cursor.o: src/lexer/cursor.c.o
.PHONY : src/lexer/cursor.o

# target to build an object file
src/lexer/cursor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/cursor.c.o
.PHONY : src/lexer/cursor.c.o

src/lexer/cursor.i: src/lexer/cursor.c.i
.PHONY : src/lexer/cursor.i

# target to preprocess a source file
src/lexer/cursor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/cursor.c.i
.PHONY : src/lexer/cursor.c.i

src/lexer/cursor.s: src/lexer/cursor.c.s
.PHONY : src/lexer/cursor.s

# target to generate assembly for a file
src/lexer/cursor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/cursor.c.s
.PHONY : src/lexer/cursor.c.s

src/lexer/lexer.o: src/lexer/lexer.c.o
.PHONY : src/lexer/lexer.o

# target to build an object file
src/lexer/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.o
.PHONY : src/lexer/lexer.c.o

src/lexer/lexer.i: src/lexer/lexer.c.i
.PHONY : src/lexer/lexer.i

# target to preprocess a source file
src/lexer/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.i
.PHONY : src/lexer/lexer.c.i

src/lexer/lexer.s: src/lexer/lexer.c.s
.PHONY : src/lexer/lexer.s

# target to generate assembly for a file
src/lexer/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.s
.PHONY : src/lexer/lexer.c.s

src/lexer/lexer_utils.o: src/lexer/lexer_utils.c.o
.PHONY : src/lexer/lexer_utils.o

# target to build an object file
src/lexer/lexer_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer_utils.c.o
.PHONY : src/lexer/lexer_utils.c.o

src/lexer/lexer_utils.i: src/lexer/lexer_utils.c.i
.PHONY : src/lexer/lexer_utils.i

# target to preprocess a source file
src/lexer/lexer_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer_utils.c.i
.PHONY : src/lexer/lexer_utils.c.i

src/lexer/lexer_utils.s: src/lexer/lexer_utils.c.s
.PHONY : src/lexer/lexer_utils.s

# target to generate assembly for a file
src/lexer/lexer_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer_utils.c.s
.PHONY : src/lexer/lexer_utils.c.s

src/lexer/lexer_utils_2.o: src/lexer/lexer_utils_2.c.o
.PHONY : src/lexer/lexer_utils_2.o

# target to build an object file
src/lexer/lexer_utils_2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer_utils_2.c.o
.PHONY : src/lexer/lexer_utils_2.c.o

src/lexer/lexer_utils_2.i: src/lexer/lexer_utils_2.c.i
.PHONY : src/lexer/lexer_utils_2.i

# target to preprocess a source file
src/lexer/lexer_utils_2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer_utils_2.c.i
.PHONY : src/lexer/lexer_utils_2.c.i

src/lexer/lexer_utils_2.s: src/lexer/lexer_utils_2.c.s
.PHONY : src/lexer/lexer_utils_2.s

# target to generate assembly for a file
src/lexer/lexer_utils_2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer_utils_2.c.s
.PHONY : src/lexer/lexer_utils_2.c.s

src/lexer/token.o: src/lexer/token.c.o
.PHONY : src/lexer/token.o

# target to build an object file
src/lexer/token.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.o
.PHONY : src/lexer/token.c.o

src/lexer/token.i: src/lexer/token.c.i
.PHONY : src/lexer/token.i

# target to preprocess a source file
src/lexer/token.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.i
.PHONY : src/lexer/token.c.i

src/lexer/token.s: src/lexer/token.c.s
.PHONY : src/lexer/token.s

# target to generate assembly for a file
src/lexer/token.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.s
.PHONY : src/lexer/token.c.s

src/lexer/token_2.o: src/lexer/token_2.c.o
.PHONY : src/lexer/token_2.o

# target to build an object file
src/lexer/token_2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_2.c.o
.PHONY : src/lexer/token_2.c.o

src/lexer/token_2.i: src/lexer/token_2.c.i
.PHONY : src/lexer/token_2.i

# target to preprocess a source file
src/lexer/token_2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_2.c.i
.PHONY : src/lexer/token_2.c.i

src/lexer/token_2.s: src/lexer/token_2.c.s
.PHONY : src/lexer/token_2.s

# target to generate assembly for a file
src/lexer/token_2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_2.c.s
.PHONY : src/lexer/token_2.c.s

src/lexer/token_3.o: src/lexer/token_3.c.o
.PHONY : src/lexer/token_3.o

# target to build an object file
src/lexer/token_3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_3.c.o
.PHONY : src/lexer/token_3.c.o

src/lexer/token_3.i: src/lexer/token_3.c.i
.PHONY : src/lexer/token_3.i

# target to preprocess a source file
src/lexer/token_3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_3.c.i
.PHONY : src/lexer/token_3.c.i

src/lexer/token_3.s: src/lexer/token_3.c.s
.PHONY : src/lexer/token_3.s

# target to generate assembly for a file
src/lexer/token_3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_3.c.s
.PHONY : src/lexer/token_3.c.s

src/lexer/token_4.o: src/lexer/token_4.c.o
.PHONY : src/lexer/token_4.o

# target to build an object file
src/lexer/token_4.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_4.c.o
.PHONY : src/lexer/token_4.c.o

src/lexer/token_4.i: src/lexer/token_4.c.i
.PHONY : src/lexer/token_4.i

# target to preprocess a source file
src/lexer/token_4.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_4.c.i
.PHONY : src/lexer/token_4.c.i

src/lexer/token_4.s: src/lexer/token_4.c.s
.PHONY : src/lexer/token_4.s

# target to generate assembly for a file
src/lexer/token_4.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_4.c.s
.PHONY : src/lexer/token_4.c.s

src/lexer/token_5.o: src/lexer/token_5.c.o
.PHONY : src/lexer/token_5.o

# target to build an object file
src/lexer/token_5.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_5.c.o
.PHONY : src/lexer/token_5.c.o

src/lexer/token_5.i: src/lexer/token_5.c.i
.PHONY : src/lexer/token_5.i

# target to preprocess a source file
src/lexer/token_5.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_5.c.i
.PHONY : src/lexer/token_5.c.i

src/lexer/token_5.s: src/lexer/token_5.c.s
.PHONY : src/lexer/token_5.s

# target to generate assembly for a file
src/lexer/token_5.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_5.c.s
.PHONY : src/lexer/token_5.c.s

src/lexer/token_getters.o: src/lexer/token_getters.c.o
.PHONY : src/lexer/token_getters.o

# target to build an object file
src/lexer/token_getters.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_getters.c.o
.PHONY : src/lexer/token_getters.c.o

src/lexer/token_getters.i: src/lexer/token_getters.c.i
.PHONY : src/lexer/token_getters.i

# target to preprocess a source file
src/lexer/token_getters.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_getters.c.i
.PHONY : src/lexer/token_getters.c.i

src/lexer/token_getters.s: src/lexer/token_getters.c.s
.PHONY : src/lexer/token_getters.s

# target to generate assembly for a file
src/lexer/token_getters.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token_getters.c.s
.PHONY : src/lexer/token_getters.c.s

src/main/main.o: src/main/main.c.o
.PHONY : src/main/main.o

# target to build an object file
src/main/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main/main.c.o
.PHONY : src/main/main.c.o

src/main/main.i: src/main/main.c.i
.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main/main.c.i
.PHONY : src/main/main.c.i

src/main/main.s: src/main/main.c.s
.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main/main.c.s
.PHONY : src/main/main.c.s

src/main/utils.o: src/main/utils.c.o
.PHONY : src/main/utils.o

# target to build an object file
src/main/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main/utils.c.o
.PHONY : src/main/utils.c.o

src/main/utils.i: src/main/utils.c.i
.PHONY : src/main/utils.i

# target to preprocess a source file
src/main/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main/utils.c.i
.PHONY : src/main/utils.c.i

src/main/utils.s: src/main/utils.c.s
.PHONY : src/main/utils.s

# target to generate assembly for a file
src/main/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main/utils.c.s
.PHONY : src/main/utils.c.s

src/parser/ast_add_funcs.o: src/parser/ast_add_funcs.c.o
.PHONY : src/parser/ast_add_funcs.o

# target to build an object file
src/parser/ast_add_funcs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_add_funcs.c.o
.PHONY : src/parser/ast_add_funcs.c.o

src/parser/ast_add_funcs.i: src/parser/ast_add_funcs.c.i
.PHONY : src/parser/ast_add_funcs.i

# target to preprocess a source file
src/parser/ast_add_funcs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_add_funcs.c.i
.PHONY : src/parser/ast_add_funcs.c.i

src/parser/ast_add_funcs.s: src/parser/ast_add_funcs.c.s
.PHONY : src/parser/ast_add_funcs.s

# target to generate assembly for a file
src/parser/ast_add_funcs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_add_funcs.c.s
.PHONY : src/parser/ast_add_funcs.c.s

src/parser/ast_add_funcs_2.o: src/parser/ast_add_funcs_2.c.o
.PHONY : src/parser/ast_add_funcs_2.o

# target to build an object file
src/parser/ast_add_funcs_2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_add_funcs_2.c.o
.PHONY : src/parser/ast_add_funcs_2.c.o

src/parser/ast_add_funcs_2.i: src/parser/ast_add_funcs_2.c.i
.PHONY : src/parser/ast_add_funcs_2.i

# target to preprocess a source file
src/parser/ast_add_funcs_2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_add_funcs_2.c.i
.PHONY : src/parser/ast_add_funcs_2.c.i

src/parser/ast_add_funcs_2.s: src/parser/ast_add_funcs_2.c.s
.PHONY : src/parser/ast_add_funcs_2.s

# target to generate assembly for a file
src/parser/ast_add_funcs_2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_add_funcs_2.c.s
.PHONY : src/parser/ast_add_funcs_2.c.s

src/parser/ast_copy.o: src/parser/ast_copy.c.o
.PHONY : src/parser/ast_copy.o

# target to build an object file
src/parser/ast_copy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_copy.c.o
.PHONY : src/parser/ast_copy.c.o

src/parser/ast_copy.i: src/parser/ast_copy.c.i
.PHONY : src/parser/ast_copy.i

# target to preprocess a source file
src/parser/ast_copy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_copy.c.i
.PHONY : src/parser/ast_copy.c.i

src/parser/ast_copy.s: src/parser/ast_copy.c.s
.PHONY : src/parser/ast_copy.s

# target to generate assembly for a file
src/parser/ast_copy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_copy.c.s
.PHONY : src/parser/ast_copy.c.s

src/parser/ast_frees.o: src/parser/ast_frees.c.o
.PHONY : src/parser/ast_frees.o

# target to build an object file
src/parser/ast_frees.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_frees.c.o
.PHONY : src/parser/ast_frees.c.o

src/parser/ast_frees.i: src/parser/ast_frees.c.i
.PHONY : src/parser/ast_frees.i

# target to preprocess a source file
src/parser/ast_frees.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_frees.c.i
.PHONY : src/parser/ast_frees.c.i

src/parser/ast_frees.s: src/parser/ast_frees.c.s
.PHONY : src/parser/ast_frees.s

# target to generate assembly for a file
src/parser/ast_frees.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_frees.c.s
.PHONY : src/parser/ast_frees.c.s

src/parser/ast_inits.o: src/parser/ast_inits.c.o
.PHONY : src/parser/ast_inits.o

# target to build an object file
src/parser/ast_inits.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_inits.c.o
.PHONY : src/parser/ast_inits.c.o

src/parser/ast_inits.i: src/parser/ast_inits.c.i
.PHONY : src/parser/ast_inits.i

# target to preprocess a source file
src/parser/ast_inits.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_inits.c.i
.PHONY : src/parser/ast_inits.c.i

src/parser/ast_inits.s: src/parser/ast_inits.c.s
.PHONY : src/parser/ast_inits.s

# target to generate assembly for a file
src/parser/ast_inits.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_inits.c.s
.PHONY : src/parser/ast_inits.c.s

src/parser/ast_prints.o: src/parser/ast_prints.c.o
.PHONY : src/parser/ast_prints.o

# target to build an object file
src/parser/ast_prints.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_prints.c.o
.PHONY : src/parser/ast_prints.c.o

src/parser/ast_prints.i: src/parser/ast_prints.c.i
.PHONY : src/parser/ast_prints.i

# target to preprocess a source file
src/parser/ast_prints.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_prints.c.i
.PHONY : src/parser/ast_prints.c.i

src/parser/ast_prints.s: src/parser/ast_prints.c.s
.PHONY : src/parser/ast_prints.s

# target to generate assembly for a file
src/parser/ast_prints.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/ast_prints.c.s
.PHONY : src/parser/ast_prints.c.s

src/parser/parser.o: src/parser/parser.c.o
.PHONY : src/parser/parser.o

# target to build an object file
src/parser/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/parser.c.o
.PHONY : src/parser/parser.c.o

src/parser/parser.i: src/parser/parser.c.i
.PHONY : src/parser/parser.i

# target to preprocess a source file
src/parser/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/parser.c.i
.PHONY : src/parser/parser.c.i

src/parser/parser.s: src/parser/parser.c.s
.PHONY : src/parser/parser.s

# target to generate assembly for a file
src/parser/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/parser.c.s
.PHONY : src/parser/parser.c.s

src/parser/utils.o: src/parser/utils.c.o
.PHONY : src/parser/utils.o

# target to build an object file
src/parser/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/utils.c.o
.PHONY : src/parser/utils.c.o

src/parser/utils.i: src/parser/utils.c.i
.PHONY : src/parser/utils.i

# target to preprocess a source file
src/parser/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/utils.c.i
.PHONY : src/parser/utils.c.i

src/parser/utils.s: src/parser/utils.c.s
.PHONY : src/parser/utils.s

# target to generate assembly for a file
src/parser/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/utils.c.s
.PHONY : src/parser/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 42sh"
	@echo "... src/builtins/break.o"
	@echo "... src/builtins/break.i"
	@echo "... src/builtins/break.s"
	@echo "... src/builtins/cd.o"
	@echo "... src/builtins/cd.i"
	@echo "... src/builtins/cd.s"
	@echo "... src/builtins/continue.o"
	@echo "... src/builtins/continue.i"
	@echo "... src/builtins/continue.s"
	@echo "... src/builtins/dot.o"
	@echo "... src/builtins/dot.i"
	@echo "... src/builtins/dot.s"
	@echo "... src/builtins/echo.o"
	@echo "... src/builtins/echo.i"
	@echo "... src/builtins/echo.s"
	@echo "... src/builtins/exit.o"
	@echo "... src/builtins/exit.i"
	@echo "... src/builtins/exit.s"
	@echo "... src/builtins/export.o"
	@echo "... src/builtins/export.i"
	@echo "... src/builtins/export.s"
	@echo "... src/builtins/true_false.o"
	@echo "... src/builtins/true_false.i"
	@echo "... src/builtins/true_false.s"
	@echo "... src/builtins/unset.o"
	@echo "... src/builtins/unset.i"
	@echo "... src/builtins/unset.s"
	@echo "... src/interpreter/environment.o"
	@echo "... src/interpreter/environment.i"
	@echo "... src/interpreter/environment.s"
	@echo "... src/interpreter/function_list.o"
	@echo "... src/interpreter/function_list.i"
	@echo "... src/interpreter/function_list.s"
	@echo "... src/interpreter/interpreter.o"
	@echo "... src/interpreter/interpreter.i"
	@echo "... src/interpreter/interpreter.s"
	@echo "... src/interpreter/redirections.o"
	@echo "... src/interpreter/redirections.i"
	@echo "... src/interpreter/redirections.s"
	@echo "... src/interpreter/variable_list.o"
	@echo "... src/interpreter/variable_list.i"
	@echo "... src/interpreter/variable_list.s"
	@echo "... src/lexer/cursor.o"
	@echo "... src/lexer/cursor.i"
	@echo "... src/lexer/cursor.s"
	@echo "... src/lexer/lexer.o"
	@echo "... src/lexer/lexer.i"
	@echo "... src/lexer/lexer.s"
	@echo "... src/lexer/lexer_utils.o"
	@echo "... src/lexer/lexer_utils.i"
	@echo "... src/lexer/lexer_utils.s"
	@echo "... src/lexer/lexer_utils_2.o"
	@echo "... src/lexer/lexer_utils_2.i"
	@echo "... src/lexer/lexer_utils_2.s"
	@echo "... src/lexer/token.o"
	@echo "... src/lexer/token.i"
	@echo "... src/lexer/token.s"
	@echo "... src/lexer/token_2.o"
	@echo "... src/lexer/token_2.i"
	@echo "... src/lexer/token_2.s"
	@echo "... src/lexer/token_3.o"
	@echo "... src/lexer/token_3.i"
	@echo "... src/lexer/token_3.s"
	@echo "... src/lexer/token_4.o"
	@echo "... src/lexer/token_4.i"
	@echo "... src/lexer/token_4.s"
	@echo "... src/lexer/token_5.o"
	@echo "... src/lexer/token_5.i"
	@echo "... src/lexer/token_5.s"
	@echo "... src/lexer/token_getters.o"
	@echo "... src/lexer/token_getters.i"
	@echo "... src/lexer/token_getters.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
	@echo "... src/main/utils.o"
	@echo "... src/main/utils.i"
	@echo "... src/main/utils.s"
	@echo "... src/parser/ast_add_funcs.o"
	@echo "... src/parser/ast_add_funcs.i"
	@echo "... src/parser/ast_add_funcs.s"
	@echo "... src/parser/ast_add_funcs_2.o"
	@echo "... src/parser/ast_add_funcs_2.i"
	@echo "... src/parser/ast_add_funcs_2.s"
	@echo "... src/parser/ast_copy.o"
	@echo "... src/parser/ast_copy.i"
	@echo "... src/parser/ast_copy.s"
	@echo "... src/parser/ast_frees.o"
	@echo "... src/parser/ast_frees.i"
	@echo "... src/parser/ast_frees.s"
	@echo "... src/parser/ast_inits.o"
	@echo "... src/parser/ast_inits.i"
	@echo "... src/parser/ast_inits.s"
	@echo "... src/parser/ast_prints.o"
	@echo "... src/parser/ast_prints.i"
	@echo "... src/parser/ast_prints.s"
	@echo "... src/parser/parser.o"
	@echo "... src/parser/parser.i"
	@echo "... src/parser/parser.s"
	@echo "... src/parser/utils.o"
	@echo "... src/parser/utils.i"
	@echo "... src/parser/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

