from tester import test_cmd

test_cmd("echo empty quotes first", "echo '' test")
test_cmd("echo no args", "echo")
test_cmd("echo no args space", "echo ")
test_cmd("echo one arg", "echo one_argument")
test_cmd("echo many args", "echo there is a lot of args OH MY GOD 1 2 3 4 5 6")
test_cmd("echo -E", "echo -E")
test_cmd("echo -E backslash 1", "echo -E \\")
test_cmd("echo -E backslash 2", "echo -E \\\\")
test_cmd("echo -E backslash 3", "echo -E \\\\\\")
test_cmd("echo -E backslash 3 quoted", "echo -E '\\\\\\'")
test_cmd("echo -E newline", "echo -E \\n")
test_cmd("echo -EeE newline", "echo -EeE \\n")
test_cmd("echo -EeE newline quoted", "echo -EeE '\\n'")
test_cmd("echo -e", "echo -e")
test_cmd("echo -e backslash 1", "echo -e \\")
test_cmd("echo -e backslash 2", "echo -e \\\\")
test_cmd("echo -e backslash 3", "echo -e \\\\\\")
test_cmd("echo -e backslash 3 quoted", "echo -e '\\\\\\'")
test_cmd("echo -e backslash many", "echo -e \\\\\\\\\\\\\\\\")
test_cmd("echo -e newline", "echo -e \\n")
test_cmd("echo -eEe newline", "echo -eEe \\n")
test_cmd("echo -n", "echo -n test test test")
test_cmd("echo echo", "echo echo test")
test_cmd("echo a lot", "echo -e -E -e -n -E -ni huhbfr ferwfew fwf")
test_cmd("echo tab", "echo -e a\\tb")
test_cmd("echo tab quoted", "echo -e 'e\\tb'")
test_cmd("echo multiple flags", "echo -n -e hello\\tworld")
test_cmd("echo flags and multiple args", "echo -n hello world")
test_cmd("echo -n flag and multiple escape sequences", "echo -n -e hello\\tworld\\nnewline")
test_cmd("echo -e flag and escape sequences", "echo -e 'hello\\tworld\\nnewline'")
test_cmd("echo -e flag real quoted tab newline", "echo -e 'hello\tworld\nnewline'")
test_cmd("echo -e flag real tab newline", "echo -e hello\tworld\nnewline")
test_cmd("echo -e flag real quoted tab", "echo -e 'hello\tworld'")
test_cmd("echo backslash space -e", "echo -e \ hello\world")
test_cmd("echo backslash space -E", "echo -e \ hello\world")
test_cmd("echo ascii house 2", "echo '|_/\\_|__|_'")
test_cmd("echo ascii house 1", "echo \"/\\\"")
test_cmd("echo ascii house 3", "echo '/\\'")
test_cmd("echo double quotes many backslash newlines", "echo \"\\\\\\\\\\\n\n\\\\\"")
test_cmd("echo double quotes many backslash newlines + chars", "echo \"\\\\\e\\\e\\\n\n\\\\\"")

#Uncomment when it pass only.
test_cmd("echo fuck malloc", "echo fuck your malloc 10000" + ("a" * 20000))

if __name__ == "__main__":
    from tester import summary
    summary()
